steps:
  # 1. Ejecutar pruebas unitarias automatizadas en backend
  - name: 'node:20-slim'
    entrypoint: 'npm'
    args: ['test']
    dir: 'backend'

  # 2. Compilar la imagen de Docker para Google Cloud Run
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/fichas-tecnicas-easycencosud:$COMMIT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/fichas-tecnicas-easycencosud:latest'
      - './backend'

  # 3. Empujar la imagen al Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/fichas-tecnicas-easycencosud:$COMMIT_SHA'

  # 4. Desplegar el servicio actualizado a Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'fichas-tecnicas-easycencosud'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/fichas-tecnicas-easycencosud:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/fichas-tecnicas-easycencosud:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/fichas-tecnicas-easycencosud:latest'

timeout: '600s'
