steps:
  # 1. Compilar la imagen de Docker para Google Cloud Run aprovechando la caché de capas
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/fichas-tecnicas-easycencosud:latest || true
        docker build --cache-from us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/fichas-tecnicas-easycencosud:latest -t us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/fichas-tecnicas-easycencosud:$COMMIT_SHA -t us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/fichas-tecnicas-easycencosud:latest ./backend

  # 2. Empujar la imagen al Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/fichas-tecnicas-easycencosud:$COMMIT_SHA'

  # 3. Desplegar el servicio actualizado a Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'fichas-tecnicas-easycencosud'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/fichas-tecnicas-easycencosud:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/fichas-tecnicas-easycencosud:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/fichas-tecnicas-easycencosud:latest'

timeout: '600s'

options:
  logging: CLOUD_LOGGING_ONLY
